name: Publish Python Package

on:
    release:
        types:
            - released

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.12.4'

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install hatch twine

            -   name: Build package
                run: |
                    hatch version patch
                    hatch build

            -   name: Publish package
                env:
                    TWINE_USERNAME: __token__
                    TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
                    TWINE_REPOSITORY: pypi
                run: |
                    twine upload dist/*

            -   name: Save changes
                run: |
                    git add .
                    git commit -m "Bump version $(hatch version)"

            -   name: Push changes
                run: |
                    git push origin main
